import { SELF } from "cloudflare:test";
import { describe, expect, it } from "vitest";

describe("management Mini App page", () => {
  it("serves secure no-store HTML with all management sections", async () => {
    const response = await SELF.fetch("https://example.test/app");
    const html = await response.text();
    expect(response.status).toBe(200);
    expect(response.headers.get("cache-control")).toBe("no-store");
    expect(response.headers.get("content-security-policy")).toContain("default-src 'none'");
    expect(response.headers.get("content-security-policy")).toContain("script-src 'self' https://telegram.org");
    expect(response.headers.get("content-security-policy")).toContain("frame-ancestors");
    expect(html).toContain("Persona 管理面板");
    expect(html).toContain("https://telegram.org/js/telegram-web-app.js");
    expect(html).toContain('data-view="overview"');
    expect(html).toContain('data-view="memories"');
    expect(html).toContain('data-view="episodes"');
    expect(html).toContain('data-view="sources"');
    expect(html).toContain('data-view="recalls"');
    expect(html).toContain('id="contact-settings"');
    expect(html).toContain('data-view="persona"');
    expect(html).toContain('data-view="drafts"');
    expect(html).toContain('data-primary="home"');
    expect(html).toContain('data-primary="memory"');
    expect(html).toContain('data-primary="relationship"');
    expect(html).toContain('data-primary="settings"');
    expect(html).toContain('data-secondary-group="memory"');
    expect(html).toContain('data-secondary-group="relationship"');
    expect(html).toContain('class="persona-avatar"');
    expect(html).toContain('src="/app/avatar"');
    expect(html).toContain('id="telegram-login"');
    expect(html).toContain("使用 Telegram 账号验证");
    expect(html).toContain("验证已绑定的 Telegram 账号");
    expect(html).toContain('aria-label="底部导航"');
    expect(html).toContain("--glass-bg");
    expect(html).toContain("backdrop-filter");
    expect(html).toContain("@supports not");
    expect(html).toContain("prefers-reduced-motion");
    expect(html).toContain("env(safe-area-inset-bottom)");
    expect(html).toContain("min-height:44px");
    expect(html).not.toContain("localStorage");
  });

  it("serves same-origin application code without caching", async () => {
    const response = await SELF.fetch("https://example.test/app.js");
    const script = await response.text();
    expect(response.status).toBe(200);
    expect(response.headers.get("cache-control")).toBe("no-store");
    expect(script).toContain("/api/app/login");
    expect(script).toContain("/api/app/session");
    expect(script).toContain("/api/app/logout");
    expect(script).toContain("window.Telegram.WebApp");
    expect(script).toContain("initData");
    expect(script).toContain("memory-conflict=");
    expect(script).toContain("/api/app/memory-conflicts/");
    expect(script).toContain("/api/app/episodes");
    expect(script).toContain("/api/app/reply-memory-usage");
    expect(script).toContain("/api/app/memory-recalls");
    expect(script).toContain("固定");
    expect(script).toContain("忽略");
    expect(script).toContain("/api/app/chat-preferences");
    expect(script).toContain("/api/app/identity-core");
    expect(script).toContain("/api/app/proactive-stats");
    expect(script).toContain("/api/app/quality-stats");
    expect(script).toContain("showPrimary");
    expect(script).toContain("showSecondary");
    expect(script).toContain("aria-selected");
    expect(script).toContain("showToast");
    expect(script).toContain("skeleton");
    expect(script).toContain("机器人在线");
    expect(script).toContain("记忆系统");
    expect(script).toContain("当前模型");
    expect(script).not.toContain("localStorage");
  });
});
